---

on:
  - pull_request

name: Run CI 🍕😋

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@94e0aab03ca135d11a35e5bfc14e6746dc56e7e9 # tag=1.1.0
      with:
        scandir: './bin'

  rubocop:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development:test
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
      with:
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake rubocop

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      COVERAGE: true
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
      with:
        bundler-cache: true
    - name: Setup config
      run: mv config/hdm.yml{.template,}
    - name: Run tests
      run: bundle exec rake test:all

  build_docker_image:
    name: 'Built test Docker image'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Build Docker image
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          push: false
